title: CARIOCHI
description: Documentation hub for Reflecto, Objecto, Recordo, Expresso
url: https://cariochi.github.io
baseurl: "" # keep empty for org/user site; set to repo name for project site
github_url: https://github.com/cariochi

# Build
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false

permalink: pretty

# Where the docs live (plain pages under /projects). This lets us autogenerate menus without defining collections.
include:
  - projects

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-toc

# jekyll-toc defaults (can be overridden per page)
toc:
  min_level: 1
  max_level: 2
  no_toc_section_class: "no-toc"
  # headings_defaults helps ensure stable IDs
  # (toc renders from page content; we also add anchors with CSS + small JS-free CSS trick)

# Defaults for all project pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: project
      toc: true
      toc_label: ""

# Navigation label for the brand
brand:
  name: CARIOCHI
  logo: /assets/images/logo.svg

# Feed
feed:
  path: feed.xml

# Exclusions
exclude:
  - README.md
  - vendor

google_analytics: G-HVN3N9W4DK
